'use strict';

export const SERVER_CONNECTION_CHANGE = 'SERVER_CONNECTION_CHANGE';
export const WINDOW_FOCUS = 'WINDOW_FOCUS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const FETCH_USERS = 'FETCH_USERS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_PATCH_USER = 'UPDATE_PATCH_USER';
export const FETCH_PINNED_MESSAGES = 'FETCH_PINNED_MESSAGES';
export const ADD_PINNED_MESSAGE = 'ADD_PINNED_MESSAGE';
export const REMOVE_PINNED_MESSAGE = 'REMOVE_PINNED_MESSAGE';
